name: Deploy to Server

on:
  push:
    branches: [ main, deployment-setup ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.SERVER_HOST }}
        username: ${{ vars.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ vars.SERVER_PORT }}
        script: |
          cd /var/www/bodo
          git pull origin main
          npm ci
          npm run db:generate
          npm run build
          pm2 restart bodo-app || pm2 start npm --name "bodo-app" -- start
